### ISSUE TITLE
Thread safe with sidekiq?

### ISSUE THREAD

**Issue by leoniddinershtein** [alloy/lowdown#5]
Hi Alloy!

I was trying to use lowdown with sidekiq with an open connection:

I have added method push_notification, which reuse existing client connection. Made lowdown client as a singleton.

```ruby
 class Lowdown::Client
  def push_notification(notification, &callback)
    connection.open unless connection.open?
    send_notification(notification, &callback)
  end
end
```

But I'm receiving "RuntimeError: Connection already open." from sidekiq workers.
Do you have any recommendations how to use lowdown with sidekiq?

**Comment by alloy** [comment]
Hey, sorry about that, I missed the notification email for this ticket.

So, I haven’t used this with sidekiq yet and I have made significant changes aimed at maintaining long lived connections. https://github.com/alloy/lowdown/blob/master/examples/long-running.rb

One thing to note is that, as this uses Celluloid, you should be using Sidekiq 4 so that there aren’t any clashes in Celluloid usage.

I’ll be doing a release of this work probably tomorrow, would be great if you can give it a try as well.

**Comment by leoniddinershtein** [comment]
I have wrote from scratch, used just one thread for opened http/2 connection. Looks like with http2 streams there is no need to have multithreads (all thread work done in http-2 gem)

Thank you very much for your gem, it was very useful to see how APNS works with http/2!

**Comment by alloy** [comment]
@leoniddinershtein Cool and you’re welcome :+1:

The reason for multiple threads is that I don’t want the callbacks to halt writing to the socket and processing the HTTP data coming back from the service. In addition, a connection pool requires threads as well. Finally, for long running connections you need some form of supervising, which Celluloid already handles nicely.

If any of these sound useful to you, then I invite you to try the current version out nonetheless and/or possibly improve it to work well for you as well.
